version: '{build}'
image:
- Visual Studio 2017
- Ubuntu
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - /release-.*/
  - /^\d+\.\d+\.\d+(-\S*)?$/
environment:
  MINVER_BUILD_METADATA: build.%APPVEYOR_BUILD_NUMBER%
build_script:
- cmd: ./build.cmd
- sh: ./build.sh
test: off
artifacts:
- path: ./**/*.nupkg
deploy: off
