on:
  push:
    branches:
      - master
      - release-*
    tags:
      - "*.*.*"
  pull_request:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-2019]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439
        with:
          dotnet-version: "3.1.402"
      - run: dotnet --info
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
      - name: Run ./build.cmd
        if: contains(matrix.os, 'windows')
        run: ./build.cmd
      - name: Run ./build.sh
        if: contains(matrix.os, 'macos') || contains(matrix.os, 'ubuntu')
        run: ./build.sh
      - if: matrix.os == 'ubuntu-18.04'
        env:
          MYGET_ADAMRALPH_CI_API_KEY: ${{ secrets.MYGET_ADAMRALPH_CI_API_KEY }}
        run: ./push.sh
