on:
  push:
    branches:
    - master
    - release-*
    tags:
    - '*.*.*'
  pull_request:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-10.15, ubuntu-18.04, windows-2019]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439
      with:
        dotnet-version: '3.1.402'
    - run: dotnet --info
    - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
    - name: Run ./build.cmd
      if: contains(matrix.runs-on, 'windows')
      run: ./build.cmd
    - name: Run ./build.sh
      if: contains(matrix.runs-on, 'macos') || contains(matrix.runs-on, 'ubuntu')
      run: ./build.sh
    - if: matrix.runs-on == 'ubuntu-18.04'
      env:
        MYGET_ADAMRALPH_CI_API_KEY: ${{ secrets.MYGET_ADAMRALPH_CI_API_KEY }}
      run: ./push.sh
